- hosts: valid
  remote_user: ansible
  gather_facts: no
  become: yes

  tasks:
  - name: testing SQL query
    mysql_query:
      db: classicmodels
      login_user: root
      login_password: ""
      query: select customerName, phone, state, country from customers
#    no_log: True
    register: query_result_all

  - debug:
      msg: "{{ query_result_all }}"
      
  - name: testing SQL query with fetchone option
    mysql_query:
      db: classicmodels
      login_user: root
      login_password: ""
      query: select customerName, phone, state, country from customers
      fetchone: true
#    no_log: True
    register: query_result_one

  - debug:
      msg: "{{ query_result_one }}"
      
  - name: testing Insert query
    mysql_query:
      db: classicmodels
      login_user: root
      login_password: ""
      query: insert into employees (employeeNumber, lastName, firstName, extension, email, officeCode, jobTitle) VALUES (1000, 'test', 'test', 'x1250', 'test@classicmodelcars.com', 7, 'Sales RP')
    #    no_log: True
    
  - name: selecting result
    mysql_query:
      db: classicmodels
      login_user: root
      login_password: ""
      query: select * from employees where lastName='test'
    #    no_log: True
    register: select_result
      
  - debug:
      msg: "{{ select_result }}"

  - name: testing delete query
    mysql_query:
      db: classicmodels
      login_user: root
      login_password: ""
      query: delete from employees where lastName='test'

  - name: selecting result
    mysql_query:
      db: classicmodels
      login_user: root
      login_password: ""
      query: select * from employees where lastName='test'
    #    no_log: True
    register: select_result
      
  - debug:
      msg: "{{ select_result }}"
      
