- hosts: valid
  remote_user: ansible
  gather_facts: no
  become: yes

  tasks:
  - name: testing SQL query
    mysql_query:
      db: classicmodels
      login_user: root
      login_password: "{{ mysql_password }}"
      query: select customerName, phone, state, country from customers
    register: query_result_all

  - debug:
      msg: "{{ query_result_all }}"
      
  - name: testing SQL query with fetchone option
    mysql_query:
      db: classicmodels
      login_user: root
      login_password: "{{ mysql_password }}"
      query: select customerName, phone, state, country from customers
      fetchone: true
    register: query_result_one

  - debug:
      msg: "{{ query_result_one }}"
      
  - name: testing SQL query with optional_args
    mysql_query:
      db: classicmodels
      login_user: root
      login_password: "{{ mysql_password }}"
      query: select * from employees where jobTitle='%s'
      positional_args:
      - President
    register: query_result_one

  - debug:
      msg: "{{ query_result_one }}"

  - name: testing SQL query with named_args
    mysql_query:
        db: classicmodels
        login_user: root
        login_password: "{{ mysql_password }}"
        query: select * from employees where jobTitle='%(job)s'
        named_args:
          job: 'Sales RP'
    register: query_result_one

  - debug:
      msg: "{{ query_result_one }}"
      
  - name: testing Insert query
    mysql_query:
      db: classicmodels
      login_user: root
      login_password: "{{ mysql_password }}"
      query: insert into employees (employeeNumber, lastName, firstName, extension, email, officeCode, jobTitle) VALUES (1000, 'test', 'test', 'x1250', 'test@classicmodelcars.com', 7, 'Sales RP')

  - name: testing Inserting the same query
    mysql_query:
      db: classicmodels
      login_user: root
      login_password: "{{ mysql_password }}"
      query: insert into employees (employeeNumber, lastName, firstName, extension, email, officeCode, jobTitle) VALUES (1000, 'test', 'test', 'x1250', 'test@classicmodelcars.com', 7, 'Sales RP')

  - name: testing Insert query with optional_args
    mysql_query:
      db: classicmodels
      login_user: root
      login_password: "{{ mysql_password }}"
      query: insert into employees (employeeNumber, lastName, firstName, extension, email, officeCode, jobTitle) VALUES (%s, %s, %s, %s, %s, %s, %s)
      positional_args:
      - 1704
      - test_lastName
      - test_Name
      - 'x1250'
      - test@classicmodelcars.com
      - 5
      - 'Sales RP'

  - name: testing Insert query with named_args
    mysql_query:
        db: classicmodels
        login_user: root
        login_password: "{{ mysql_password }}"
        query: insert into employees (employeeNumber, lastName, firstName, extension, email, officeCode, jobTitle) VALUES ('%(num)s', '%(last_name)s', '%(first_name)s', '%(ext)s', '%(email)s', '%(code)s', '%(job)s')
        named_args:
          num: 1705
          last_name: lastName_test
          first_name: Name_test
          ext: 'x1250'
          email: test@classicmodelcars.com
          code: 5
          job: 'Sales RP'
  
  - name: selecting result
    mysql_query:
      db: classicmodels
      login_user: root
      login_password: "{{ mysql_password }}"
      query: select * from employees where lastName in ('test', 'test_lastName', 'lastName_test')
    register: select_result
      
  - debug:
      msg: "{{ select_result }}" 

  - name: testing delete query
    mysql_query:
      db: classicmodels
      login_user: root
      login_password: "{{ mysql_password }}"
      query: delete from employees where lastName='test'

  - name: testing delete the same query
    mysql_query:
      db: classicmodels
      login_user: root
      login_password: "{{ mysql_password }}"
      query: delete from employees where lastName='test'

  - name: selecting result
    mysql_query:
      db: classicmodels
      login_user: root
      login_password: "{{ mysql_password }}"
      query: select * from employees where lastName='test'
    register: select_result
      
  - debug:
      msg: "{{ select_result }}"

  - name: updating a row
    mysql_query:
      db: classicmodels
      config_file: '/root/.my.cnf'
      query: update offices set city='Tunis' where officeCode='2'

  - name: updating with the same query
    mysql_query:
      db: classicmodels
      config_file: '/root/.my.cnf'
      query: update offices set city='Tunis' where officeCode='2'

  - name: selecting result
    mysql_query:
      db: classicmodels
      login_user: root
      login_password: "{{ mysql_password }}"
      query: select city from offices where officeCode='2'
    register: select_result

  - debug:
      msg: "{{ select_result }}"

      
